name: Unit tests

on:
  pull_request:
  push:

jobs:

  test:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [ 3.7, 3.9, "3.10" ]
        os:  [ macos-latest, ubuntu-20.04, ubuntu-22.04]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Mayavi install all dependencies and backends on Ubuntu 20.04
        if: matrix.os == 'ubuntu-20.04'
        run: |
              sudo apt-get update -y && sudo apt-get install -y \
                  xvfb \
                  xserver-xephyr \
                  tigervnc-standalone-server \
                  x11-utils \
                  gnumeric \
                  && apt-get clean -y

      - name: Mayavi Qt platform plugin xcb for mayavi on Ubuntu 20.04
        if: matrix.os == 'ubuntu-20.04'
        run: |
              sudo apt-get update -y && sudo apt-get install -y \
                  xvfb \
                  xserver-xephyr \
                  tigervnc-standalone-server \
                  x11-utils \
                  gnumeric \
                  && apt-get clean -y

      - name: Install pip deps
        shell: bash -l {0}
        run: |
            pip3 install -r requirements.txt

      - name: Run tests
        working-directory: .
        run: |
            pip3 install pytest-cov
            python3 -m pytest --cov=crumbs --cov-report=xml --cov-branch tests

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          working-directory: crumbs
          fail_ci_if_error: true
          flags: tests
          name: codecov-umbrella
          verbose: true
